-- Script de sauvegarde : copie toutes les tables dans des tables persistantes BKP_
-- Bases : SOC, STG, TCH, WRK

EXECUTE IMMEDIATE $$
BEGIN
    -- SOC.PUBLIC
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_ADDR AS SELECT * FROM SOC.PUBLIC.O_ADDR;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_CONS AS SELECT * FROM SOC.PUBLIC.O_CONS;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_HOSP AS SELECT * FROM SOC.PUBLIC.O_HOSP;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_INDV AS SELECT * FROM SOC.PUBLIC.O_INDV;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_STFF AS SELECT * FROM SOC.PUBLIC.O_STFF;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_TELP AS SELECT * FROM SOC.PUBLIC.O_TELP;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_O_TRET AS SELECT * FROM SOC.PUBLIC.O_TRET;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_R_MEDC AS SELECT * FROM SOC.PUBLIC.R_MEDC;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_R_PART AS SELECT * FROM SOC.PUBLIC.R_PART;
    CREATE OR REPLACE TABLE SOC.PUBLIC.BKP_R_ROOM AS SELECT * FROM SOC.PUBLIC.R_ROOM;

    -- STG.PUBLIC
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_CHAMBRE AS SELECT * FROM STG.PUBLIC.CHAMBRE;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_CONSULTATION AS SELECT * FROM STG.PUBLIC.CONSULTATION;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_HOSPITALISATION AS SELECT * FROM STG.PUBLIC.HOSPITALISATION;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_MEDICAMENT AS SELECT * FROM STG.PUBLIC.MEDICAMENT;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_PATIENT AS SELECT * FROM STG.PUBLIC.PATIENT;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_PERSONNEL AS SELECT * FROM STG.PUBLIC.PERSONNEL;
    CREATE OR REPLACE TABLE STG.PUBLIC.BKP_TRAITEMENT AS SELECT * FROM STG.PUBLIC.TRAITEMENT;

    -- TCH.PUBLIC
    CREATE OR REPLACE TABLE TCH.PUBLIC.BKP_T_SUIV_RUN AS SELECT * FROM TCH.PUBLIC.T_SUIV_RUN;
    CREATE OR REPLACE TABLE TCH.PUBLIC.BKP_T_SUIV_TRMT AS SELECT * FROM TCH.PUBLIC.T_SUIV_TRMT;

    -- WRK.PUBLIC
    CREATE OR REPLACE TABLE WRK.PUBLIC.BKP_WRK_MEDC AS SELECT * FROM WRK.PUBLIC.WRK_MEDC;
    CREATE OR REPLACE TABLE WRK.PUBLIC.BKP_WRK_PART AS SELECT * FROM WRK.PUBLIC.WRK_PART;
    CREATE OR REPLACE TABLE WRK.PUBLIC.BKP_WRK_ROOM AS SELECT * FROM WRK.PUBLIC.WRK_ROOM;
END;
$$;
