-- Script pour supprimer toutes les tables (DROP)
-- Bases : SOC, STG, TCH, WRK

EXECUTE IMMEDIATE $$
BEGIN
    -- SOC.PUBLIC
    DROP TABLE IF EXISTS SOC.PUBLIC.O_ADDR;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_CONS;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_HOSP;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_INDV;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_STFF;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_TELP;
    DROP TABLE IF EXISTS SOC.PUBLIC.O_TRET;
    DROP TABLE IF EXISTS SOC.PUBLIC.R_MEDC;
    DROP TABLE IF EXISTS SOC.PUBLIC.R_PART;
    DROP TABLE IF EXISTS SOC.PUBLIC.R_ROOM;

    -- STG.PUBLIC
    DROP TABLE IF EXISTS STG.PUBLIC.CHAMBRE;
    DROP TABLE IF EXISTS STG.PUBLIC.CONSULTATION;
    DROP TABLE IF EXISTS STG.PUBLIC.HOSPITALISATION;
    DROP TABLE IF EXISTS STG.PUBLIC.MEDICAMENT;
    DROP TABLE IF EXISTS STG.PUBLIC.PATIENT;
    DROP TABLE IF EXISTS STG.PUBLIC.PERSONNEL;
    DROP TABLE IF EXISTS STG.PUBLIC.TRAITEMENT;

    -- TCH.PUBLIC
    DROP TABLE IF EXISTS TCH.PUBLIC.T_SUIV_RUN;
    DROP TABLE IF EXISTS TCH.PUBLIC.T_SUIV_TRMT;

    -- WRK.PUBLIC
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_MEDC;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_PART;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_ROOM;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_TRET;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_ADDR;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_CONS;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_INDV;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_STFF;
    DROP TABLE IF EXISTS WRK.PUBLIC.WRK_HOSP;
END;
$$;
