-- Script de restauration : recrée les tables depuis les BKP_ puis les supprime
-- Bases : SOC, STG, TCH, WRK

EXECUTE IMMEDIATE $$
BEGIN
    -- Restauration SOC.PUBLIC
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_ADDR AS SELECT * FROM SOC.PUBLIC.BKP_O_ADDR;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_CONS AS SELECT * FROM SOC.PUBLIC.BKP_O_CONS;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_HOSP AS SELECT * FROM SOC.PUBLIC.BKP_O_HOSP;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_INDV AS SELECT * FROM SOC.PUBLIC.BKP_O_INDV;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_STFF AS SELECT * FROM SOC.PUBLIC.BKP_O_STFF;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_TELP AS SELECT * FROM SOC.PUBLIC.BKP_O_TELP;
    CREATE OR REPLACE TABLE SOC.PUBLIC.O_TRET AS SELECT * FROM SOC.PUBLIC.BKP_O_TRET;
    CREATE OR REPLACE TABLE SOC.PUBLIC.R_MEDC AS SELECT * FROM SOC.PUBLIC.BKP_R_MEDC;
    CREATE OR REPLACE TABLE SOC.PUBLIC.R_PART AS SELECT * FROM SOC.PUBLIC.BKP_R_PART;
    CREATE OR REPLACE TABLE SOC.PUBLIC.R_ROOM AS SELECT * FROM SOC.PUBLIC.BKP_R_ROOM;

    -- Restauration STG.PUBLIC
    CREATE OR REPLACE TABLE STG.PUBLIC.CHAMBRE AS SELECT * FROM STG.PUBLIC.BKP_CHAMBRE;
    CREATE OR REPLACE TABLE STG.PUBLIC.CONSULTATION AS SELECT * FROM STG.PUBLIC.BKP_CONSULTATION;
    CREATE OR REPLACE TABLE STG.PUBLIC.HOSPITALISATION AS SELECT * FROM STG.PUBLIC.BKP_HOSPITALISATION;
    CREATE OR REPLACE TABLE STG.PUBLIC.MEDICAMENT AS SELECT * FROM STG.PUBLIC.BKP_MEDICAMENT;
    CREATE OR REPLACE TABLE STG.PUBLIC.PATIENT AS SELECT * FROM STG.PUBLIC.BKP_PATIENT;
    CREATE OR REPLACE TABLE STG.PUBLIC.PERSONNEL AS SELECT * FROM STG.PUBLIC.BKP_PERSONNEL;
    CREATE OR REPLACE TABLE STG.PUBLIC.TRAITEMENT AS SELECT * FROM STG.PUBLIC.BKP_TRAITEMENT;

    -- Restauration TCH.PUBLIC
    CREATE OR REPLACE TABLE TCH.PUBLIC.T_SUIV_RUN AS SELECT * FROM TCH.PUBLIC.BKP_T_SUIV_RUN;
    CREATE OR REPLACE TABLE TCH.PUBLIC.T_SUIV_TRMT AS SELECT * FROM TCH.PUBLIC.BKP_T_SUIV_TRMT;

    -- Restauration WRK.PUBLIC
    CREATE OR REPLACE TABLE WRK.PUBLIC.WRK_MEDC AS SELECT * FROM WRK.PUBLIC.BKP_WRK_MEDC;
    CREATE OR REPLACE TABLE WRK.PUBLIC.WRK_PART AS SELECT * FROM WRK.PUBLIC.BKP_WRK_PART;
    CREATE OR REPLACE TABLE WRK.PUBLIC.WRK_ROOM AS SELECT * FROM WRK.PUBLIC.BKP_WRK_ROOM;

    -- Nettoyage : suppression des tables BKP_
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_ADDR;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_CONS;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_HOSP;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_INDV;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_STFF;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_TELP;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_O_TRET;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_R_MEDC;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_R_PART;
    DROP TABLE IF EXISTS SOC.PUBLIC.BKP_R_ROOM;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_CHAMBRE;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_CONSULTATION;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_HOSPITALISATION;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_MEDICAMENT;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_PATIENT;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_PERSONNEL;
    DROP TABLE IF EXISTS STG.PUBLIC.BKP_TRAITEMENT;
    DROP TABLE IF EXISTS TCH.PUBLIC.BKP_T_SUIV_RUN;
    DROP TABLE IF EXISTS TCH.PUBLIC.BKP_T_SUIV_TRMT;
    DROP TABLE IF EXISTS WRK.PUBLIC.BKP_WRK_MEDC;
    DROP TABLE IF EXISTS WRK.PUBLIC.BKP_WRK_PART;
    DROP TABLE IF EXISTS WRK.PUBLIC.BKP_WRK_ROOM;
END;
$$;
