-- Script de test : vérifie l'état des tables après les opérations
-- Affiche le nombre de tables et de lignes par base/schéma (hors BKP_)

SELECT TABLE_CATALOG AS base_de_donnees,
       TABLE_SCHEMA AS schema,
       TABLE_NAME AS table_name,
       ROW_COUNT AS nb_lignes
FROM (
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM SOC.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME NOT LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM STG.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME NOT LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM TCH.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME NOT LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM WRK.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME NOT LIKE 'BKP_%'
)
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;

-- EMPTY : vider la table WRK_TRET
TRUNCATE TABLE WRK_TRET;

-- REMOVE : supprimer la table WRK_TRET
DROP TABLE WRK_TRET;
