-- Script de vérification des tables de sauvegarde (BKP_)
-- Affiche les tables BKP_ existantes et leur nombre de lignes

SELECT TABLE_CATALOG AS base_de_donnees,
       TABLE_SCHEMA AS schema,
       TABLE_NAME AS table_sauvegarde,
       ROW_COUNT AS nb_lignes
FROM (
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM SOC.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM STG.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM TCH.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE 'BKP_%'
    UNION ALL
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM WRK.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE 'BKP_%'
)
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;
