SELECT 'CHAMBRE' AS table_name, COUNT(*) AS row_count FROM STG.PUBLIC.CHAMBRE
UNION ALL SELECT 'CONSULTATION', COUNT(*) FROM STG.PUBLIC.CONSULTATION
UNION ALL SELECT 'HOSPITALISATION', COUNT(*) FROM STG.PUBLIC.HOSPITALISATION
UNION ALL SELECT 'MEDICAMENT', COUNT(*) FROM STG.PUBLIC.MEDICAMENT
UNION ALL SELECT 'PATIENT', COUNT(*) FROM STG.PUBLIC.PATIENT
UNION ALL SELECT 'PERSONNEL', COUNT(*) FROM STG.PUBLIC.PERSONNEL
UNION ALL SELECT 'TRAITEMENT', COUNT(*) FROM STG.PUBLIC.TRAITEMENT