// MPD Staging pour https://dbdiagram.io

Table STG.CHAMBRE {
  NO_CHAMBRE    INTEGER      [not null]
  NOM_CHAMBRE   VARCHAR(20)  [not null]
  NO_ETAGE      BYTEINT      [not null]
  NOM_BATIMENT  VARCHAR(20)  [not null]
  TYPE_CHAMBRE  VARCHAR(10)
  PRIX_JOUR     SMALLINT     [not null]
  DT_CREATION   DATE         [not null]
}

Table STG.TRAITEMENT {
  ID_TRAITEMENT          INTEGER          [not null]
  CD_MEDICAMENT          INTEGER          [not null]
  CATG_MEDICAMENT        VARCHAR(100)     [not null]
  MARQUE_FABRI           VARCHAR(100)     [not null]
  QTE_MEDICAMENT         SMALLINT
  DSC_POSOLOGIE          VARCHAR(100)     [not null]
  ID_CONSULT             INTEGER          [not null]
  TS_CREATION_TRAITEMENT TIMESTAMP(0)     [not null]
}

Table STG.PERSONNEL {
  ID_PERSONNEL          INTEGER          [not null]
  NOM_PERSONNEL         VARCHAR(100)     [not null]
  PRENOM_PERSONNEL      VARCHAR(100)     [not null]
  FONCTION_PERSONNEL    VARCHAR(50)      [not null]
  TS_DEBUT_ACTIVITE     TIMESTAMP(0)     [not null]
  TS_FIN_ACTIVITE       TIMESTAMP(0)
  RAISON_FIN_ACTIVITE   VARCHAR(100)
  TS_CREATION_PERSONNEL TIMESTAMP(0)     [not null]
  TS_MAJ_PERSONNEL      TIMESTAMP(0)     [not null]
  CD_STATUT_PERSONNEL   VARCHAR(10)      [not null]
}

Table STG.PATIENT {
  ID_PATIENT          INTEGER          [not null]
  NOM_PATIENT         VARCHAR(100)     [not null]
  PRENOM_PATIENT      VARCHAR(100)     [not null]
  DT_NAISS            DATE             
  VILLE_NAISS         VARCHAR(100)
  PAYS_NAISS          VARCHAR(100)
  NUM_SECU            VARCHAR(15)
  IND_PAYS_NUM_TELP   VARCHAR(5)
  NUM_TELEPHONE       VARCHAR(20)
  NUM_VOIE            VARCHAR(10)
  DSC_VOIE            VARCHAR(250)
  CMPL_VOIE           VARCHAR(250)
  CD_POSTAL           VARCHAR(10)
  VILLE               VARCHAR(100)
  PAYS                VARCHAR(100)
  TS_CREATION_PATIENT TIMESTAMP(0)     [not null]
  TS_MAJ_PATIENT      TIMESTAMP(0)     [not null]
}

Table STG.CONSULTATION {
  ID_CONSULT       INTEGER          [not null]
  ID_PERSONNEL     INTEGER          [not null]
  ID_PATIENT       INTEGER          [not null]
  TS_DEBUT_CONSULT TIMESTAMP(0)     [not null]
  TS_FIN_CONSULT   TIMESTAMP(0)     [not null]
  POIDS_PATIENT    INTEGER          [not null]
  TEMP_PATIENT     INTEGER    
  UNIT_TEMP        VARCHAR(15)
  TENSION_PATIENT  INTEGER
  DSC_PATHO        VARCHAR(250)
  INDIC_DIABETE    VARCHAR(10)
  ID_TRAITEMENT    INTEGER
  INDIC_HOSPI      VARCHAR(10)
}

Table STG.HOSPITALISATION {
  ID_HOSPI          INTEGER      [not null]
  ID_CONSULT        INTEGER      [not null]
  NO_CHAMBRE        SMALLINT     [not null]
  TS_DEBUT_HOSPI    TIMESTAMP(0) [not null]
  TS_FIN_HOSPI      TIMESTAMP(0) [not null]
  COUT_HOSPI        INTEGER      [not null]
  ID_PERSONNEL_RESP INTEGER      [not null]
}

Table STG.MEDICAMENT {
  CD_MEDICAMENT     VARCHAR(10)   [not null]
  NOM_MEDICAMENT    VARCHAR(250)  [not null]
  CONDIT_MEDICAMENT  VARCHAR(100)  [not null]
  CATG_MEDICAMENT   VARCHAR(100)   [not null]
  MARQUE_FABRI      VARCHAR(100)   [not null]
}

