-- Création des bases de données du projet NF26
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS STG;
CREATE DATABASE IF NOT EXISTS SOC;
CREATE DATABASE IF NOT EXISTS TCH;
CREATE DATABASE IF NOT EXISTS WRK;  